"use client";

import { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useSession } from "next-auth/react";
import { Sparkles, Layout, Globe, Code, Download, Send, Plus, Upload, Loader2, Maximize2, Trash2, Shield, Check, Copy, Smartphone, Monitor } from "lucide-react";
import { useRouter } from "next/navigation";
import JSZip from "jszip";
import { saveAs } from "file-saver";

export default function BuilderPage() {
  const { data: session, status } = useSession();
  const router = useRouter();
  
  // App States
  const [prompt, setPrompt] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedHtml, setGeneratedHtml] = useState("");
  const [vibe, setVibe] = useState("sleek");
  const [device, setDevice] = useState<"desktop" | "mobile">("desktop");
  const [showLimitModal, setShowLimitModal] = useState(false);
  const [copied, setCopied] = useState(false);
  const [logoUrl, setLogoUrl] = useState("");
  const [isUploading, setIsUploading] = useState(false);
  const [history, setHistory] = useState<any[]>([]);
  const [currentSlug, setCurrentSlug] = useState("");
  const [currentId, setCurrentId] = useState("");
  const [showShareTooltip, setShowShareTooltip] = useState(false);
  const [contactInfo, setContactInfo] = useState("");
  const [refinePrompt, setRefinePrompt] = useState("");
  const [isRefining, setIsRefining] = useState(false);
  const [isPublic, setIsPublic] = useState(true);

  // Streaming Ref
  const abortControllerRef = useRef<AbortController | null>(null);

  useEffect(() => {
    if (status === "unauthenticated") {
      router.push("/");
    } else if (status === "authenticated") {
      fetchHistory();
    }
  }, [status, router]);

  const fetchHistory = async () => {
    try {
      const res = await fetch("/api/websites");
      const data = await res.json();
      setHistory(data);
    } catch (error) {
      console.error("Failed to fetch history", error);
    }
  };

  const handleToggleVisibility = async (val: boolean) => {
    if (!currentId) return;
    setIsPublic(val);
    try {
      await fetch("/api/websites/toggle-visibility", {
        method: "POST",
        body: JSON.stringify({ websiteId: currentId, isPublic: val }),
      });
      fetchHistory();
    } catch (error) {
      console.error("Failed to toggle visibility", error);
    }
  };

  const loadFromHistory = (site: any) => {
    setGeneratedHtml(site.html);
    setVibe(site.vibe || "sleek");
    setCurrentSlug(site.slug);
    setCurrentId(site._id);
    setIsPublic(site.isPublic ?? true);
  };

  const shareSite = () => {
    if (!currentSlug) return;
    const url = `${window.location.origin}/${currentSlug}`;
    navigator.clipboard.writeText(url);
    setShowShareTooltip(true);
    setTimeout(() => setShowShareTooltip(false), 3000);
  };

  const handleLogoUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setIsUploading(true);
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onloadend = async () => {
      try {
        const res = await fetch("/api/upload", {
          method: "POST",
          body: JSON.stringify({ image: reader.result }),
        });
        const data = await res.json();
        setLogoUrl(data.url);
      } catch (error) {
        console.error("Upload failed", error);
      } finally {
        setIsUploading(false);
      }
    };
  };

  const copyCode = () => {
    navigator.clipboard.writeText(generatedHtml);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadZip = async () => {
    const zip = new JSZip();
    
    // Create professional structure
    const assets = zip.folder("assets");
    
    // Extract base HTML content vs styles if possible (optional simplification)
    // For now, we provide the full index.html and a copy for reference
    zip.file("index.html", generatedHtml);
    zip.file("README.md", `# Generated by VibeBuilder\n\nThis website was generated using AI at VibeBuilder.\n\n## Customization\nYou can edit the Tailwind classes directly in the index.html file.`);
    
    const content = await zip.generateAsync({ type: "blob" });
    saveAs(content, "vibe-builder-project.zip");
  };

  const sanitizeHtml = (html: string) => {
    // Strip markdown code blocks if they exist
    let clean = html.trim();
    if (clean.startsWith('```html')) {
      clean = clean.replace(/^```html/, '');
    } else if (clean.startsWith('```')) {
      clean = clean.replace(/^```/, '');
    }
    if (clean.endsWith('```')) {
      clean = clean.replace(/```$/, '');
    }
    return clean;
  };

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    
    // Check limit first
    if (session?.user && session.user.sitesCount >= (session.user.maxSites || 5)) {
      setShowLimitModal(true);
      return;
    }

    setIsGenerating(true);
    setGeneratedHtml(""); // Clear previous
    setCurrentId(""); // Reset ID for new gen
    
    // Abort previous stream if any
    if (abortControllerRef.current) abortControllerRef.current.abort();
    abortControllerRef.current = new AbortController();

    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        body: JSON.stringify({ 
          prompt, 
          contactInfo,
          ownerId: session?.user?.id,
          vibe,
          logoUrl 
        }),
        signal: abortControllerRef.current.signal,
      });

      if (response.status === 403) {
        setShowLimitModal(true);
        return;
      }

      if (!response.body) return;

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let streamedHtml = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        
        const chunk = decoder.decode(value);
        const lines = chunk.split("\n").filter(line => line.trim() !== "");
        for (const line of lines) {
            if (line.startsWith('0:')) {
                const text = JSON.parse(line.substring(2));
                streamedHtml += text;
                setGeneratedHtml(sanitizeHtml(streamedHtml));
            }
        }
      }

      fetchHistory();

      // After generation, we don't have the ID immediately from the stream. 
      // The history fetch will eventually give us the latest ID, 
      // but for refinement we'll need to load it or wait for history.
      // Optimization: The history API returns sorted, so data[0] is our new site.
      const freshHistoryResponse = await fetch("/api/websites");
      const freshData = await freshHistoryResponse.json();
      if (freshData.length > 0) {
        setCurrentId(freshData[0]._id);
        setCurrentSlug(freshData[0].slug);
        setIsPublic(true); // Default for new gen
      }

    } catch (error: any) {
      if (error.name !== 'AbortError') {
        console.error("Generation failed", error);
      }
    } finally {
      setIsGenerating(false);
    }
  };

  const handleRefine = async () => {
    if (!refinePrompt.trim() || !currentId) return;

    // Check limit
    if (session?.user && session.user.sitesCount >= (session.user.maxSites || 5)) {
      setShowLimitModal(true);
      return;
    }

    setIsRefining(true);
    
    if (abortControllerRef.current) abortControllerRef.current.abort();
    abortControllerRef.current = new AbortController();

    try {
      const response = await fetch("/api/generate/refine", {
        method: "POST",
        body: JSON.stringify({ 
          websiteId: currentId,
          instruction: refinePrompt
        }),
        signal: abortControllerRef.current.signal,
      });

      if (response.status === 403) {
        setShowLimitModal(true);
        return;
      }

      if (!response.body) return;

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let streamedHtml = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        
        const chunk = decoder.decode(value);
        const lines = chunk.split("\n").filter(line => line.trim() !== "");
        for (const line of lines) {
            if (line.startsWith('0:')) {
                const text = JSON.parse(line.substring(2));
                streamedHtml += text;
                setGeneratedHtml(sanitizeHtml(streamedHtml));
            }
        }
      }

      setRefinePrompt(""); // Clear after success
      fetchHistory();
    } catch (error: any) {
      if (error.name !== 'AbortError') {
        console.error("Refinement failed", error);
      }
    } finally {
      setIsRefining(false);
    }
  };

  if (status === "loading") return <div className="h-screen w-screen flex items-center justify-center bg-black"><Loader2 className="w-10 h-10 animate-spin text-purple-500" /></div>;

  return (
    <div className="flex h-screen bg-[#050505] text-white overflow-hidden font-sans">
      {/* Sidebar */}
      <motion.aside 
        initial={{ x: -20, opacity: 0 }}
        animate={{ x: 0, opacity: 1 }}
        className="w-[420px] border-r border-white/5 bg-[#0a0a0a] flex flex-col p-6 overflow-y-auto shrink-0 z-20 shadow-2xl relative"
      >
        <div className="flex items-center gap-4 mb-10 group cursor-pointer">
          <div className="w-10 h-10 rounded-xl bg-white/5 border border-white/5 overflow-hidden group-hover:scale-110 transition-all">
            <img src="/logo.png" className="w-full h-full object-cover p-1" />
          </div>
          <h2 className="text-xl font-black uppercase tracking-tighter italic">VibeBuilder</h2>
        </div>

        <div className="flex-1 flex flex-col gap-8">
          {/* Design Vibe Selector */}
          <div className="flex flex-col gap-3">
             <label className="text-xs font-black uppercase tracking-widest text-gray-500">Pick Your Vibe</label>
             <div className="grid grid-cols-3 gap-2">
                {[
                  { id: "sleek", label: "Sleek" },
                  { id: "glassmorphism", label: "Glass" },
                  { id: "brutalist", label: "Brutal" }
                ].map((v) => (
                  <button
                    key={v.id}
                    onClick={() => setVibe(v.id)}
                    className={`py-3 rounded-xl border text-[11px] font-bold transition-all ${
                      vibe === v.id 
                        ? "bg-white text-black border-white shadow-xl shadow-white/5" 
                        : "bg-white/5 border-white/10 text-gray-500 hover:bg-white/10"
                    }`}
                  >
                    {v.label}
                  </button>
                ))}
             </div>
          </div>

          <div className="flex flex-col gap-3">
            <label className="text-xs font-black uppercase tracking-widest text-gray-500 flex justify-between">
              Your Vision
              <span className="bg-purple-500/10 px-2 py-0.5 rounded text-purple-400 border border-purple-500/10">
                 Quota: {Math.max(0, (session?.user?.maxSites || 5) - (session?.user?.sitesCount || 0))} left
              </span>
            </label>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="Describe your elite vision... (e.g., A luxury dark-themed real estate portal with gold accents, smooth entrance animations, and a high-converting hero section)"
              className="w-full h-40 p-4 rounded-2xl bg-white/5 border border-white/10 focus:border-purple-500/50 focus:ring-1 focus:ring-purple-500/50 transition-all outline-none resize-none text-sm placeholder:text-gray-600"
            />
          </div>

          <div className="flex flex-col gap-3">
            <label className="text-xs font-black uppercase tracking-widest text-gray-500">Contact Info (Optional)</label>
            <input
              type="text"
              value={contactInfo}
              onChange={(e) => setContactInfo(e.target.value)}
              placeholder="e.g. +92332965814 or hello@example.com"
              className="w-full px-4 py-3 rounded-xl bg-white/5 border border-white/10 focus:border-purple-500/50 outline-none text-sm placeholder:text-gray-700 transition-all font-medium"
            />
          </div>

          <div className="flex flex-col gap-3">
            <label className="text-xs font-black uppercase tracking-widest text-gray-500">Add Assets</label>
            <input 
              type="file" 
              id="logo-upload" 
              className="hidden" 
              accept="image/*" 
              onChange={handleLogoUpload}
            />
            <label 
              htmlFor="logo-upload"
              className="aspect-video rounded-3xl border-2 border-dashed border-white/10 bg-white/5 flex flex-col items-center justify-center gap-3 group hover:border-purple-500/30 hover:bg-purple-500/5 transition-all cursor-pointer relative overflow-hidden"
            >
              {logoUrl ? (
                <img src={logoUrl} className="w-full h-full object-contain p-4" />
              ) : isUploading ? (
                <Loader2 className="w-8 h-8 animate-spin text-purple-500" />
              ) : (
                <>
                  <Upload className="w-5 h-5 text-gray-500 group-hover:text-purple-400 transition-colors" />
                  <span className="text-[10px] font-bold uppercase tracking-widest text-gray-500 group-hover:text-gray-300">Upload Logo</span>
                </>
              )}
            </label>
          </div>

          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            disabled={isGenerating || isRefining || !prompt}
            onClick={handleGenerate}
            className="w-full py-4 rounded-2xl bg-white text-black font-black uppercase text-sm tracking-widest flex items-center justify-center gap-3 group disabled:opacity-50 disabled:grayscale cursor-pointer shadow-lg shadow-white/10"
          >
            {isGenerating ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                <span>Generating...</span>
              </>
            ) : (
              <>
                <Plus className="w-5 h-5" />
                <span>New Project</span>
              </>
            )}
          </motion.button>

          {/* Refine Section */}
          <AnimatePresence>
            {generatedHtml && (
              <motion.div 
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="flex flex-col gap-3 p-4 rounded-[28px] bg-gradient-to-b from-purple-500/10 to-transparent border border-purple-500/20"
              >
                <label className="text-[10px] font-black uppercase tracking-[0.2em] text-purple-400 mb-1">Refine this Design</label>
                <textarea
                  value={refinePrompt}
                  onChange={(e) => setRefinePrompt(e.target.value)}
                  placeholder="Ask to change colors, add sections, fixed layouts..."
                  className="w-full h-24 bg-transparent text-sm outline-none resize-none placeholder:text-gray-700 font-medium"
                />
                <button 
                  disabled={isRefining || isGenerating || !refinePrompt}
                  onClick={handleRefine}
                  className="w-full py-3 rounded-xl bg-purple-600 text-white text-[11px] font-black uppercase tracking-widest flex items-center justify-center gap-2 hover:bg-purple-500 transition-colors disabled:opacity-30 shadow-lg shadow-purple-600/20"
                >
                  {isRefining ? <Loader2 className="w-3 h-3 animate-spin" /> : <Sparkles className="w-3 h-3" />}
                  {isRefining ? 'Refining...' : 'Apply Vibe'}
                </button>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Recent Creations */}
          {history.length > 0 && (
            <div className="flex flex-col gap-4 mt-8 pb-10">
              <label className="text-[10px] font-black uppercase tracking-[0.2em] text-gray-600">Recent Creations</label>
              <div className="flex flex-col gap-2">
                {history.map((site: any) => (
                  <button
                    key={site.slug}
                    onClick={() => loadFromHistory(site)}
                    className="p-4 rounded-2xl bg-white/5 border border-white/5 hover:border-purple-500/30 transition-all text-left group"
                  >
                    <div className="flex justify-between items-center mb-1">
                      <p className="text-[11px] font-black truncate text-gray-300 group-hover:text-white uppercase tracking-tight">{site.title || site.slug}</p>
                      <div className="w-1.5 h-1.5 rounded-full bg-purple-500 shrink-0" />
                    </div>
                    <p className="text-[9px] text-gray-600 font-bold uppercase tracking-widest">{site.vibe} Vibe</p>
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>

        <div className="mt-auto pt-6 border-t border-white/5 flex items-center gap-4">
          <img src={session?.user?.image || ""} className="w-10 h-10 rounded-xl border border-white/10 shadow-lg" />
          <div className="flex-1">
            <p className="text-sm font-black truncate leading-none mb-1">{session?.user?.name}</p>
            <p className="text-[9px] text-gray-500 uppercase tracking-widest">{session?.user?.role} • {session?.user?.isPremium ? 'Premium' : 'Free'}</p>
          </div>
          <button onClick={() => router.push("/")} className="p-2 rounded-lg hover:bg-white/5 text-gray-600 transition-colors">
            <Maximize2 className="w-4 h-4" />
          </button>
        </div>
      </motion.aside>

      {/* Preview */}
      <main className="flex-1 relative flex flex-col min-w-0 bg-[#0c0c0c]">
        <header className="h-20 px-8 border-b border-white/5 flex items-center justify-between bg-black/50 backdrop-blur-md z-10 shrink-0">
          <div className="flex items-center gap-8">
            <div className="flex items-center gap-3 p-1 rounded-xl bg-white/5 border border-white/10">
              <button 
                onClick={() => setDevice("desktop")}
                className={`p-2 rounded-lg transition-all ${device === "desktop" ? "bg-white text-black shadow-lg" : "text-gray-500 hover:text-white"}`}
              >
                <Monitor className="w-4 h-4" />
              </button>
              <button 
                onClick={() => setDevice("mobile")}
                className={`p-2 rounded-lg transition-all ${device === "mobile" ? "bg-white text-black shadow-lg" : "text-gray-500 hover:text-white"}`}
              >
                <Smartphone className="w-4 h-4" />
              </button>
            </div>
            <div className="h-6 w-px bg-white/5" />
            
            {currentId && (
              <div className="flex items-center gap-4">
                <button 
                  onClick={() => handleToggleVisibility(!isPublic)}
                  className={`flex items-center gap-2 px-3 py-1.5 rounded-lg border transition-all ${
                    isPublic 
                      ? "bg-emerald-500/10 border-emerald-500/20 text-emerald-400" 
                      : "bg-white/5 border-white/10 text-gray-500"
                  }`}
                >
                  <div className={`w-1.5 h-1.5 rounded-full ${isPublic ? "bg-emerald-500 animate-pulse" : "bg-gray-600"}`} />
                  <span className="text-[10px] font-black uppercase tracking-widest">
                    {isPublic ? "Public Discovery" : "Private Site"}
                  </span>
                </button>
                <div className="h-6 w-px bg-white/5" />
              </div>
            )}

            <div className="flex items-center gap-2 text-[10px] font-black tracking-widest text-gray-500 uppercase">
              <Globe className="w-3 h-3 text-purple-500" />
              Live Preview
            </div>
          </div>

          <div className="flex items-center gap-4">
             {generatedHtml && (
                <>
                  <button 
                    onClick={copyCode}
                    className="p-3 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 transition-all"
                    title="Copy Code"
                  >
                    {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4 text-gray-400" />}
                  </button>
                  <button 
                    onClick={downloadZip}
                    className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-xs font-bold transition-all"
                  >
                    <Download className="w-4 h-4" />
                    ZIP Bundle
                  </button>
                  <div className="relative">
                    <button 
                      onClick={shareSite}
                      className="flex items-center gap-3 px-6 py-2.5 rounded-xl bg-purple-600 text-white hover:bg-purple-700 transition-all shadow-xl shadow-purple-600/30 font-black uppercase text-[10px] tracking-widest"
                    >
                      <Send className="w-3.5 h-3.5" />
                      Share Public Link
                    </button>
                    <AnimatePresence>
                      {showShareTooltip && (
                        <motion.div
                          initial={{ opacity: 0, scale: 0.9, y: 10 }}
                          animate={{ opacity: 1, scale: 1, y: 0 }}
                          exit={{ opacity: 0, scale: 0.9, y: 10 }}
                          className="absolute bottom-full right-0 mb-3 px-4 py-2 bg-white text-black text-[10px] font-black uppercase tracking-widest rounded-lg shadow-2xl z-50 whitespace-nowrap"
                        >
                          Public Link Copied!
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                </>
             )}
          </div>
        </header>

        <div className="flex-1 p-10 overflow-hidden flex items-center justify-center relative bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] bg-fixed opacity-90">
          <AnimatePresence mode="wait">
            {!generatedHtml && !isGenerating ? (
              <motion.div 
                key="empty"
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.95 }}
                className="w-full max-w-lg text-center p-12"
              >
                <div className="w-24 h-24 rounded-[40px] bg-gradient-to-br from-purple-500/10 to-blue-500/10 flex items-center justify-center mx-auto mb-10 border border-white/5 shadow-2xl">
                  <Layout className="w-10 h-10 text-gray-600" />
                </div>
                <h3 className="text-3xl font-black mb-4 tracking-tight uppercase italic">Empty Canvas</h3>
                <p className="text-gray-500 leading-relaxed text-sm">
                  Your AI-generated website will stream right here. Describe your vision to begin.
                </p>
              </motion.div>
            ) : (
              <motion.div 
                key="rendered"
                animate={{ 
                  width: device === "desktop" ? "100%" : "375px",
                  height: device === "desktop" ? "100%" : "667px",
                  maxWidth: device === "desktop" ? "1200px" : "375px"
                }}
                transition={{ type: "spring", stiffness: 100, damping: 20 }}
                className="rounded-[32px] overflow-hidden bg-[#0a0a0a] shadow-[0_0_100px_rgba(0,0,0,0.5)] ring-1 ring-white/10 relative group border border-white/5 flex flex-col"
              >
                {/* Browser Top Bar */}
                <div className="h-10 px-6 border-b border-white/10 bg-black/60 backdrop-blur-3xl flex items-center gap-4 relative z-20 shrink-0">
                  <div className="flex gap-2">
                    <div className="w-2.5 h-2.5 rounded-full bg-red-500/50" />
                    <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/50" />
                    <div className="w-2.5 h-2.5 rounded-full bg-emerald-500/50" />
                  </div>
                  <div className="flex-1 max-w-sm mx-auto h-6 bg-white/5 rounded-lg border border-white/5 flex items-center px-4">
                    <p className="text-[10px] text-gray-500 font-mono truncate tracking-tight">{currentSlug ? `vibebuilder.com/${currentSlug}` : 'Generating Visual Identity...'}</p>
                  </div>
                  <div className="flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    <div className="w-4 h-0.5 bg-gray-700 rounded-full" />
                    <div className="w-4 h-0.5 bg-gray-700 rounded-full" />
                  </div>
                </div>

                <div className="flex-1 relative bg-white">
                  {isGenerating && (
                      <div className="absolute top-4 right-4 z-20 flex items-center gap-2 bg-black/80 backdrop-blur-md px-4 py-2 rounded-full border border-white/10 shadow-2xl">
                          <Loader2 className="w-3 h-3 animate-spin text-purple-500" />
                          <span className="text-[9px] font-black uppercase text-gray-200 tracking-widest">AI Engine Coding...</span>
                      </div>
                  )}
                  {isRefining && (
                      <div className="absolute top-4 right-4 z-20 flex items-center gap-2 bg-purple-600/90 backdrop-blur-md px-4 py-2 rounded-full border border-white/10 shadow-2xl">
                          <Sparkles className="w-3 h-3 animate-pulse text-white" />
                          <span className="text-[9px] font-black uppercase text-white tracking-widest">Refining Layout...</span>
                      </div>
                  )}
                  <iframe
                    srcDoc={generatedHtml}
                    className="w-full h-full border-none"
                    title="Site Preview"
                  />
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </main>

      {/* Limit Modal */}
      {showLimitModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-6 bg-black/90 backdrop-blur-2xl">
          <motion.div 
            initial={{ y: 50, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            className="w-full max-w-md bg-[#0a0a0a] border border-white/10 rounded-[48px] p-12 text-center shadow-2xl relative overflow-hidden"
          >
             <div className="absolute top-0 left-0 w-full h-1.5 bg-gradient-to-r from-purple-600 to-blue-600" />
             <div className="w-24 h-24 rounded-[40px] bg-purple-500/10 border border-purple-500/20 flex items-center justify-center mx-auto mb-10 shadow-lg">
                <Shield className="w-12 h-12 text-purple-400" />
             </div>
             <h2 className="text-4xl font-black mb-4 uppercase italic tracking-tighter">Frozen</h2>
             <p className="text-gray-500 mb-12 leading-relaxed text-sm font-medium">
                You've reached your generation limit. Please contact the administrator on WhatsApp to unfreeze your account and add more site credits.
             </p>
             <div className="flex flex-col gap-4">
                <a 
                  href="https://wa.me/92332965814?text=I%20want%20to%20unfreeze%20my%20VibeBuilder%20account"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="w-full py-5 rounded-[24px] bg-emerald-500 text-white font-black uppercase text-sm tracking-widest hover:scale-[1.02] active:scale-95 transition-transform shadow-xl shadow-emerald-500/20 flex items-center justify-center gap-3"
                >
                   <Send className="w-5 h-5" />
                   Message +92332965814
                </a>
                <button 
                  onClick={() => setShowLimitModal(false)}
                  className="w-full py-5 rounded-[24px] bg-white/5 border border-white/10 text-gray-600 font-black uppercase text-[10px] tracking-[0.2em] hover:bg-white/10 transition-all outline-none"
                >
                   Stay Free
                </button>
             </div>
          </motion.div>
        </div>
      )}
    </div>
  );
}
