"use client";

import { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useSession } from "next-auth/react";
import { Sparkles, Layout, Globe, Code, Download, Send, Plus, Upload, Loader2, Maximize2, Trash2, Shield, Check, Copy, Smartphone, Monitor } from "lucide-react";
import { useRouter } from "next/navigation";
import JSZip from "jszip";
import { saveAs } from "file-saver";

export default function BuilderPage() {
  const { data: session, status } = useSession();
  const router = useRouter();
  
  // App States
  const [prompt, setPrompt] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedHtml, setGeneratedHtml] = useState("");
  const [vibe, setVibe] = useState("sleek");
  const [device, setDevice] = useState<"desktop" | "mobile">("desktop");
  const [showLimitModal, setShowLimitModal] = useState(false);
  const [copied, setCopied] = useState(false);
  const [logoUrl, setLogoUrl] = useState("");
  const [isUploading, setIsUploading] = useState(false);

  // Streaming Ref
  const abortControllerRef = useRef<AbortController | null>(null);

  useEffect(() => {
    if (status === "unauthenticated") {
      router.push("/");
    }
  }, [status, router]);

  const handleLogoUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setIsUploading(true);
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onloadend = async () => {
      try {
        const res = await fetch("/api/upload", {
          method: "POST",
          body: JSON.stringify({ image: reader.result }),
        });
        const data = await res.json();
        setLogoUrl(data.url);
      } catch (error) {
        console.error("Upload failed", error);
      } finally {
        setIsUploading(false);
      }
    };
  };

  const copyCode = () => {
    navigator.clipboard.writeText(generatedHtml);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadZip = async () => {
    const zip = new JSZip();
    
    // Create professional structure
    const assets = zip.folder("assets");
    
    // Extract base HTML content vs styles if possible (optional simplification)
    // For now, we provide the full index.html and a copy for reference
    zip.file("index.html", generatedHtml);
    zip.file("README.md", `# Generated by VibeBuilder\n\nThis website was generated using AI at VibeBuilder.\n\n## Customization\nYou can edit the Tailwind classes directly in the index.html file.`);
    
    const content = await zip.generateAsync({ type: "blob" });
    saveAs(content, "vibe-builder-project.zip");
  };

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    
    // Check limit first
    if (session?.user && !session.user.isPremium && session.user.sitesCount >= 5) {
      setShowLimitModal(true);
      return;
    }

    setIsGenerating(true);
    setGeneratedHtml(""); // Clear previous
    
    // Abort previous stream if any
    if (abortControllerRef.current) abortControllerRef.current.abort();
    abortControllerRef.current = new AbortController();

    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        body: JSON.stringify({ 
          prompt, 
          ownerId: session?.user?.id,
          vibe,
          logoUrl 
        }),
        signal: abortControllerRef.current.signal,
      });

      if (response.status === 403) {
        setShowLimitModal(true);
        return;
      }

      if (!response.body) return;

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let streamedHtml = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        
        const chunk = decoder.decode(value);
        // The AI SDK sends data in a specific format (e.g., 0:"text"), we extract the text part
        const lines = chunk.split("\n").filter(line => line.trim() !== "");
        for (const line of lines) {
            if (line.startsWith('0:')) {
                const text = JSON.parse(line.substring(2));
                streamedHtml += text;
                setGeneratedHtml(streamedHtml);
            }
        }
      }

    } catch (error: any) {
      if (error.name !== 'AbortError') {
        console.error("Generation failed", error);
      }
    } finally {
      setIsGenerating(false);
    }
  };

  if (status === "loading") return <div className="h-screen w-screen flex items-center justify-center bg-black"><Loader2 className="w-10 h-10 animate-spin text-purple-500" /></div>;

  return (
    <div className="flex h-screen bg-[#050505] text-white overflow-hidden font-sans">
      {/* Sidebar */}
      <motion.aside 
        initial={{ x: -20, opacity: 0 }}
        animate={{ x: 0, opacity: 1 }}
        className="w-[420px] border-r border-white/5 bg-[#0a0a0a] flex flex-col p-6 overflow-y-auto shrink-0 z-20 shadow-2xl relative"
      >
        <div className="flex items-center gap-3 mb-10">
          <div className="p-2 rounded-lg bg-gradient-to-br from-purple-500/20 to-blue-500/20 border border-purple-500/20">
            <Sparkles className="w-5 h-5 text-purple-400" />
          </div>
          <h2 className="text-xl font-bold tracking-tight">VibeBuilder</h2>
        </div>

        <div className="flex-1 flex flex-col gap-8">
          {/* Design Vibe Selector */}
          <div className="flex flex-col gap-3">
             <label className="text-xs font-black uppercase tracking-widest text-gray-500">Pick Your Vibe</label>
             <div className="grid grid-cols-3 gap-2">
                {[
                  { id: "sleek", label: "Sleek" },
                  { id: "glassmorphism", label: "Glass" },
                  { id: "brutalist", label: "Brutal" }
                ].map((v) => (
                  <button
                    key={v.id}
                    onClick={() => setVibe(v.id)}
                    className={`py-3 rounded-xl border text-[11px] font-bold transition-all ${
                      vibe === v.id 
                        ? "bg-white text-black border-white shadow-xl shadow-white/5" 
                        : "bg-white/5 border-white/10 text-gray-500 hover:bg-white/10"
                    }`}
                  >
                    {v.label}
                  </button>
                ))}
             </div>
          </div>

          <div className="flex flex-col gap-3">
            <label className="text-xs font-black uppercase tracking-widest text-gray-500 flex justify-between">
              Your Vision
              <span className="bg-purple-500/10 px-2 py-0.5 rounded text-purple-400 border border-purple-500/10">Free: {5 - (session?.user?.sitesCount || 0)} left</span>
            </label>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="Ex: A luxury dark barbershop with gold accents and a booking button..."
              className="w-full h-40 p-4 rounded-2xl bg-white/5 border border-white/10 focus:border-purple-500/50 focus:ring-1 focus:ring-purple-500/50 transition-all outline-none resize-none text-sm placeholder:text-gray-600"
            />
          </div>

          <div className="flex flex-col gap-3">
            <label className="text-xs font-black uppercase tracking-widest text-gray-500">Add Assets</label>
            <input 
              type="file" 
              id="logo-upload" 
              className="hidden" 
              accept="image/*" 
              onChange={handleLogoUpload}
            />
            <label 
              htmlFor="logo-upload"
              className="aspect-video rounded-3xl border-2 border-dashed border-white/10 bg-white/5 flex flex-col items-center justify-center gap-3 group hover:border-purple-500/30 hover:bg-purple-500/5 transition-all cursor-pointer relative overflow-hidden"
            >
              {logoUrl ? (
                <img src={logoUrl} className="w-full h-full object-contain p-4" />
              ) : isUploading ? (
                <Loader2 className="w-8 h-8 animate-spin text-purple-500" />
              ) : (
                <>
                  <Upload className="w-5 h-5 text-gray-500 group-hover:text-purple-400 transition-colors" />
                  <span className="text-[10px] font-bold uppercase tracking-widest text-gray-500 group-hover:text-gray-300">Upload Logo</span>
                </>
              )}
            </label>
          </div>

          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            disabled={isGenerating || !prompt}
            onClick={handleGenerate}
            className="w-full py-4 rounded-2xl bg-gradient-to-r from-purple-600 to-blue-600 text-white font-black uppercase text-sm tracking-widest flex items-center justify-center gap-3 group disabled:opacity-50 disabled:grayscale cursor-pointer shadow-lg shadow-purple-600/10"
          >
            {isGenerating ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                <span>Generating...</span>
              </>
            ) : (
              <>
                <Sparkles className="w-5 h-5" />
                <span>Build Website</span>
              </>
            )}
          </motion.button>
        </div>

        <div className="mt-auto pt-6 border-t border-white/5 flex items-center gap-4">
          <img src={session?.user?.image || ""} className="w-10 h-10 rounded-xl border border-white/10 shadow-lg" />
          <div className="flex-1">
            <p className="text-sm font-black truncate leading-none mb-1">{session?.user?.name}</p>
            <p className="text-[9px] text-gray-500 uppercase tracking-widest">{session?.user?.role} • {session?.user?.isPremium ? 'Premium' : 'Free'}</p>
          </div>
          <button onClick={() => router.push("/")} className="p-2 rounded-lg hover:bg-white/5 text-gray-600 transition-colors">
            <Maximize2 className="w-4 h-4" />
          </button>
        </div>
      </motion.aside>

      {/* Preview */}
      <main className="flex-1 relative flex flex-col min-w-0 bg-[#0c0c0c]">
        <header className="h-20 px-8 border-b border-white/5 flex items-center justify-between bg-black/50 backdrop-blur-md z-10 shrink-0">
          <div className="flex items-center gap-8">
            <div className="flex items-center gap-3 p-1 rounded-xl bg-white/5 border border-white/10">
              <button 
                onClick={() => setDevice("desktop")}
                className={`p-2 rounded-lg transition-all ${device === "desktop" ? "bg-white text-black shadow-lg" : "text-gray-500 hover:text-white"}`}
              >
                <Monitor className="w-4 h-4" />
              </button>
              <button 
                onClick={() => setDevice("mobile")}
                className={`p-2 rounded-lg transition-all ${device === "mobile" ? "bg-white text-black shadow-lg" : "text-gray-500 hover:text-white"}`}
              >
                <Smartphone className="w-4 h-4" />
              </button>
            </div>
            <div className="h-6 w-px bg-white/5" />
            <div className="flex items-center gap-2 text-[10px] font-black tracking-widest text-gray-500 uppercase">
              <Globe className="w-3 h-3 text-purple-500" />
              Live Preview
            </div>
          </div>

          <div className="flex items-center gap-4">
             {generatedHtml && (
                <>
                  <button 
                    onClick={copyCode}
                    className="p-3 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 transition-all"
                    title="Copy Code"
                  >
                    {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4 text-gray-400" />}
                  </button>
                  <button 
                    onClick={downloadZip}
                    className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 text-xs font-bold transition-all"
                  >
                    <Download className="w-4 h-4" />
                    ZIP Bundle
                  </button>
                </>
             )}
             <button 
               disabled={!generatedHtml}
               className="px-6 py-2.5 rounded-xl bg-white text-black text-xs font-black uppercase tracking-widest transition-all shadow-2xl shadow-white/5 disabled:opacity-50"
             >
                Publish
             </button>
          </div>
        </header>

        <div className="flex-1 p-10 overflow-hidden flex items-center justify-center relative">
          <AnimatePresence mode="wait">
            {!generatedHtml && !isGenerating ? (
              <motion.div 
                key="empty"
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.95 }}
                className="w-full max-w-lg text-center p-12"
              >
                <div className="w-24 h-24 rounded-[40px] bg-gradient-to-br from-purple-500/10 to-blue-500/10 flex items-center justify-center mx-auto mb-10 border border-white/5 shadow-2xl">
                  <Layout className="w-10 h-10 text-gray-600" />
                </div>
                <h3 className="text-3xl font-black mb-4 tracking-tight uppercase italic italic">Empty Canvas</h3>
                <p className="text-gray-500 leading-relaxed text-sm">
                  Your AI-generated website will stream right here. Describe your vision to begin.
                </p>
              </motion.div>
            ) : (
              <motion.div 
                key="rendered"
                animate={{ 
                  width: device === "desktop" ? "100%" : "375px",
                  height: device === "desktop" ? "100%" : "667px",
                }}
                transition={{ type: "spring", stiffness: 100, damping: 20 }}
                className="rounded-[32px] overflow-hidden bg-white shadow-2xl ring-1 ring-white/10 relative group"
              >
                {isGenerating && (
                    <div className="absolute top-4 right-4 z-20 flex items-center gap-2 bg-black/80 backdrop-blur-md px-3 py-1.5 rounded-full border border-white/10">
                        <Loader2 className="w-3 h-3 animate-spin text-purple-500" />
                        <span className="text-[9px] font-black uppercase text-gray-400">AI Streaming...</span>
                    </div>
                )}
                <iframe
                  srcDoc={generatedHtml}
                  className="w-full h-full border-none"
                  title="Site Preview"
                />
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </main>

      {/* Limit Modal */}
      {showLimitModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-6 bg-black/90 backdrop-blur-2xl">
          <motion.div 
            initial={{ y: 50, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            className="w-full max-w-md bg-[#0a0a0a] border border-white/10 rounded-[48px] p-12 text-center shadow-2xl relative overflow-hidden"
          >
             <div className="absolute top-0 left-0 w-full h-1.5 bg-gradient-to-r from-purple-600 to-blue-600" />
             <div className="w-24 h-24 rounded-[40px] bg-purple-500/10 border border-purple-500/20 flex items-center justify-center mx-auto mb-10 shadow-lg">
                <Shield className="w-12 h-12 text-purple-400" />
             </div>
             <h2 className="text-4xl font-black mb-4 uppercase italic">Frozen</h2>
             <p className="text-gray-500 mb-12 leading-relaxed text-sm font-medium">
                You've hit the 5-site limit. Upgrade to unlock unlimited generations and premium vibes.
             </p>
             <div className="flex flex-col gap-4">
                <button className="w-full py-5 rounded-[24px] bg-white text-black font-black uppercase text-sm tracking-widest hover:scale-[1.02] active:scale-95 transition-transform shadow-xl shadow-white/10">
                   Get Premium - $10
                </button>
                <button 
                  onClick={() => setShowLimitModal(false)}
                  className="w-full py-5 rounded-[24px] bg-white/5 border border-white/10 text-gray-600 font-black uppercase text-[10px] tracking-[0.2em] hover:bg-white/10 transition-all outline-none"
                >
                   Stay Free
                </button>
             </div>
          </motion.div>
        </div>
      )}
    </div>
  );
}
