"use client";

import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { ArrowRight, Loader2 } from "lucide-react";
import Link from "next/link";

export default function ExploreSection() {
  const [sites, setSites] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/websites/showcase")
      .then(res => res.json())
      .then(data => {
        if (Array.isArray(data)) {
          setSites(data);
        }
      })
      .catch(err => console.error("Failed to load showcase", err))
      .finally(() => setLoading(false));
  }, []);

  const containerVariants: any = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
        delayChildren: 0.1
      }
    }
  };

  const cardVariants: any = {
    hidden: { opacity: 0, scale: 0.95, y: 30 },
    visible: { 
      opacity: 1, 
      scale: 1, 
      y: 0,
      transition: { duration: 0.6, ease: "easeOut" }
    }
  };

  if (loading) return (
    <div className="py-20 flex justify-center">
      <Loader2 className="w-8 h-8 animate-spin text-purple-500" />
    </div>
  );

  return (
    <section id="explore" className="py-32 px-6 max-w-[1600px] mx-auto scroll-mt-20">
      <motion.div 
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, margin: "-100px" }}
        variants={containerVariants}
        className="flex flex-col md:flex-row items-end justify-between mb-20 gap-8"
      >
        <div className="space-y-4">
          <motion.h2 variants={cardVariants} className="text-5xl md:text-7xl font-black italic uppercase tracking-tighter leading-none">
            Explore <br />
            <span className="text-purple-500">The Vibe</span>
          </motion.h2>
          <motion.p variants={cardVariants} className="text-gray-500 text-sm font-bold uppercase tracking-[0.3em]">Discovery Engine • Real-time Creations</motion.p>
        </div>
        <motion.div variants={cardVariants} className="max-w-md text-right md:text-left">
           <p className="text-gray-400 text-sm leading-relaxed font-medium">
             Dive into a curated selection of premium websites generated by the community. Every site is unique, responsive, and ready for launch.
           </p>
        </motion.div>
      </motion.div>

      <motion.div 
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, margin: "-100px" }}
        variants={containerVariants}
        className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6"
      >
        {sites.map((site, i) => (
          <motion.div
            key={site._id}
            variants={cardVariants}
            className="group relative rounded-[40px] overflow-hidden bg-[#0a0a0a] border border-white/5 hover:border-purple-500/30 transition-all flex flex-col h-full"
          >
            <div className="aspect-[4/5] bg-gradient-to-br from-[#0c0c0c] to-[#050505] flex items-center justify-center p-6 overflow-hidden relative">
               <div className="absolute inset-0 opacity-10 group-hover:opacity-20 transition-opacity bg-[url('https://www.transparenttextures.com/patterns/cubes.png')]" />
                              <div className="w-full h-full rounded-2xl border border-white/10 shadow-2xl bg-black/40 backdrop-blur-3xl flex flex-col translate-y-12 group-hover:translate-y-4 transition-all duration-700 overflow-hidden relative pointer-events-none">
                  {/* Browser Top Bar */}
                  <div className="h-4 px-3 border-b border-white/10 bg-black/60 backdrop-blur-3xl flex items-center gap-1.5 relative z-10 shrink-0">
                    <div className="w-1.5 h-1.5 rounded-full bg-red-500/50" />
                    <div className="w-1.5 h-1.5 rounded-full bg-yellow-500/50" />
                    <div className="w-1.5 h-1.5 rounded-full bg-emerald-500/50" />
                  </div>
                  
                  {/* Live Iframe Preview */}
                  <div className="flex-1 bg-white relative">
                    <iframe 
                      src={`/${site.slug}`}
                      className="absolute top-0 left-0 w-[1200px] h-[1500px] origin-top-left scale-[0.25] md:scale-[0.22] lg:scale-[0.2] xl:scale-[0.22] border-none"
                      loading="lazy"
                      title={site.title}
                    />
                    
                    {/* Subtle Overlay to make it feel like a preview */}
                    <div className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent pointer-events-none" />
                  </div>

                  {/* Vibe Badge */}
                  <div className="absolute bottom-4 left-4 right-4 z-10">
                     <div className="bg-black/80 backdrop-blur-md px-3 py-1.5 rounded-lg border border-white/10 inline-flex items-center gap-2">
                        <div className="w-1.5 h-1.5 rounded-full bg-purple-500" />
                        <span className="text-[8px] font-black uppercase tracking-widest text-gray-300">{site.vibe || 'sleek'} vibe</span>
                     </div>
                  </div>
                </div>
            </div>

            <div className="p-8 bg-black/50 backdrop-blur-xl flex flex-col gap-6 mt-auto">
              <div className="flex justify-between items-start">
                <div>
                  <p className="font-black text-lg tracking-tight mb-2 uppercase italic">{site.slug}</p>
                  <div className="flex items-center gap-2">
                    <img src={site.ownerId?.image || "/logo.png"} className="w-5 h-5 rounded-lg border border-white/10" />
                    <span className="text-[10px] font-black uppercase tracking-widest text-gray-400 group-hover:text-purple-400 transition-colors">{site.ownerId?.name || "Anonymous Creator"}</span>
                  </div>
                </div>
                <Link 
                  href={`/${site.slug}`}
                  className="w-12 h-12 rounded-2xl bg-white text-black flex items-center justify-center hover:scale-110 active:scale-95 transition-all shadow-xl shadow-white/10 hover:bg-purple-500 hover:text-white"
                >
                  <ArrowRight className="w-5 h-5" />
                </Link>
              </div>
            </div>
          </motion.div>
        ))}
      </motion.div>
    </section>
  );
}
